name: rr_project
channels:
  - defaults
dependencies:
  - atomicwrites=1.4.0
  - attrs=21.4.0
  - certifi=2021.5.30
  - colorama=0.4.4
  - importlib_metadata=4.8.1
  - iniconfig=1.1.1
  - more-itertools=8.12.0
  - packaging=21.3
  - pip=21.2.2
  - pluggy=0.13.1
  - py=1.11.0
  - pyparsing=3.0.4
  - pytest=6.2.4
  - python=3.6.13
  - setuptools=58.0.4
  - sqlite=3.38.3
  - toml=0.10.2
  - typing_extensions=4.1.1
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - wincertstore=0.2
  - zipp=3.6.0
  - pip:
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - black==22.3.0
    - bs4==0.0.1
    - charset-normalizer==2.0.12
    - chromedriver-autoinstaller==0.3.1
    - click==8.0.4
    - dataclasses==0.8
    - decorator==5.1.1
    - geckodriver-autoinstaller==0.1.0
    - idna==3.3
    - importlib-metadata==4.8.3
    - ipython==7.16.3
    - ipython-genutils==0.2.0
    - jedi==0.17.2
    - lxml==4.8.0
    - mypy-extensions==0.4.3
    - numpy==1.19.5
    - pandas==1.1.5
    - parso==0.7.1
    - pathspec==0.9.0
    - pickleshare==0.7.5
    - platformdirs==2.4.0
    - prompt-toolkit==3.0.29
    - pygments==2.12.0
    - python-dateutil==2.8.2
    - pytz==2022.1
    - requests==2.27.1
    - selenium==3.141.0
    - six==1.16.0
    - soupsieve==2.3.2.post1
    - tomli==1.2.3
    - traitlets==4.3.3
    - typed-ast==1.5.3
    - urllib3==1.26.9
    - wcwidth==0.2.5
    - websockets==9.1
